//! Settings (spec 023): the desktop's second-level nav and its eight panels.
//!
//! Same split the contacts module uses — `fixtures` is the canonical data read
//! off `design/settings/*.png`, `components` the reusable visuals — and the
//! page state lives in `wallet::page`, which already owns the three-column
//! shell this section slots into as a `Section::Settings` switch.
//!
//! Nothing here reaches for a preference store. Every value is a fixture, so
//! the later "wire real settings" feature replaces `fixtures.rs` and leaves
//! the visuals alone.

pub mod components;
pub mod fixtures;
pub mod live;

use gpui::SharedString;

use crate::loc::Loc;

/// Every settings string the desktop renders, resolved once per locale.
///
/// Most of these keys predate this feature: the `settings.*` namespace has
/// shipped since the React Native app, and `settingsModals.*`, `about.*` and
/// `assets.rpcFix*` all describe screens these mocks redraw. Spec 023 added
/// the storage namespace, the network-list chrome and a handful of labels.
pub struct SettingsStrings {
    pub title: SharedString,
    // second-level nav
    pub nav_account: SharedString,
    pub nav_appearance: SharedString,
    pub nav_localization: SharedString,
    pub nav_networks: SharedString,
    pub nav_rpc_providers: SharedString,
    pub nav_endpoints: SharedString,
    pub nav_storage: SharedString,
    pub nav_about: SharedString,
    // account panel
    pub accounts_total: String,
    pub accounts_count: String,
    pub account_create: SharedString,
    pub account_sign_in: SharedString,
    pub sign_out_button: SharedString,
    pub sign_out_desc: SharedString,
    pub erase_title: SharedString,
    pub erase_subtitle: SharedString,
    pub erase_confirm: SharedString,
    // appearance panel
    pub language: SharedString,
    pub theme_title: SharedString,
    pub theme_light: SharedString,
    pub theme_dark: SharedString,
    pub theme_auto: SharedString,
    pub avatar_title: SharedString,
    pub avatar_initials: SharedString,
    pub avatar_identicon: SharedString,
    pub text_scale: SharedString,
    // localization panel
    pub currency: SharedString,
    pub number_format: SharedString,
    pub number_subtitle: SharedString,
    pub date_format: SharedString,
    pub time_format: SharedString,
    pub note_system: SharedString,
    pub note_automatic: SharedString,
    pub note_indian: SharedString,
    // networks panel
    pub networks_subtitle: SharedString,
    pub add_network: SharedString,
    pub add_network_desc: SharedString,
    pub search_placeholder: SharedString,
    pub chain_id: String,
    pub rpc_url: SharedString,
    pub explorer: SharedString,
    pub network_custom: SharedString,
    /// The prefix a slow endpoint's pill wears: "Slower · 1.2s".
    pub network_slow: SharedString,
    pub network_save_hint: SharedString,
    pub compatible: SharedString,
    pub compatibility_check: SharedString,
    pub check_safe: SharedString,
    pub check_signer: SharedString,
    pub check_remaining: String,
    pub custom_rpc_title: SharedString,
    pub custom_rpc_placeholder: SharedString,
    pub best_rpc: String,
    // rpc providers panel
    pub providers_desc: SharedString,
    pub provider_connected: SharedString,
    pub provider_not_set: SharedString,
    pub provider_check_key: SharedString,
    pub provider_get_key: SharedString,
    pub provider_supports: String,
    pub provider_avg_latency: String,
    // endpoints panel
    pub endpoints_desc: SharedString,
    pub endpoint_chain_data: SharedString,
    pub endpoint_chain_data_hint: SharedString,
    pub endpoint_passkey: SharedString,
    pub endpoint_passkey_hint: SharedString,
    pub endpoint_relay: SharedString,
    pub endpoint_relay_hint: SharedString,
    pub endpoint_fiat: SharedString,
    pub endpoint_fiat_hint: SharedString,
    pub endpoints_reset: SharedString,
    pub endpoints_guide: SharedString,
    // storage panel
    pub storage_subtitle: SharedString,
    pub storage_summary: String,
    pub storage_user_data: SharedString,
    pub storage_caches: SharedString,
    pub storage_connections: SharedString,
    pub item_transactions: SharedString,
    pub item_contacts: SharedString,
    pub item_custom: SharedString,
    pub item_browsing: SharedString,
    pub item_balances: SharedString,
    pub item_rates: SharedString,
    pub item_scan: SharedString,
    pub item_dapps: SharedString,
    pub count_records: String,
    pub count_contacts: String,
    pub count_items: String,
    pub count_sites: String,
    pub storage_clear: SharedString,
    pub storage_clear_all: SharedString,
    pub storage_disconnect_all: SharedString,
    // about panel
    pub about_tagline: SharedString,
    pub about_version: String,
    pub about_section_technical: SharedString,
    pub about_section_links: SharedString,
    pub about_wallet_label: SharedString,
    pub about_wallet_value: SharedString,
    pub about_auth_label: SharedString,
    pub about_auth_value: SharedString,
    pub about_account_label: SharedString,
    pub about_account_value: SharedString,
    pub about_signer_label: SharedString,
    pub about_signer_value: SharedString,
    pub about_networks_label: SharedString,
    pub about_networks_value: String,
    pub about_link_website: SharedString,
    pub about_link_github: SharedString,
    pub about_link_safe: SharedString,
    pub about_footer: SharedString,
    // rescue (DSR1)
    pub rpc_fix_title: SharedString,
    pub rpc_fix_warning: SharedString,
    pub rpc_fix_label: SharedString,
    pub rpc_fix_save: SharedString,
    pub rpc_providers_hint: SharedString,
    pub rpc_report: SharedString,
    pub rpc_unavailable_multiple: String,
    pub rpc_fix_action: SharedString,
    pub offline: SharedString,
}

impl SettingsStrings {
    pub fn resolve(loc: &Loc) -> Self {
        let s = |key: &str| loc.t(key);
        let raw = |key: &str| loc.t(key).to_string();
        Self {
            title: s("settings.title"),
            nav_account: s("settings.sections.account"),
            nav_appearance: s("settings.sections.appearance"),
            nav_localization: s("settings.sections.localization"),
            nav_networks: s("settings.advanced.networksTitle"),
            nav_rpc_providers: s("settings.advanced.rpcProvidersTitle"),
            nav_endpoints: s("settings.advanced.endpointsTitle"),
            nav_storage: s("settings.storage.title"),
            nav_about: s("settings.about.title"),
            accounts_total: raw("settingsModals.account.total"),
            accounts_count: raw("home.switcherAccountCount"),
            account_create: s("settingsModals.account.createNew"),
            account_sign_in: s("settingsModals.account.signInExisting"),
            sign_out_button: s("settings.signOut.button"),
            sign_out_desc: s("settings.signOut.desc"),
            erase_title: s("settings.eraseDevice.title"),
            erase_subtitle: s("settings.eraseDevice.subtitle"),
            erase_confirm: s("settings.eraseDevice.confirm"),
            language: s("language.title"),
            theme_title: s("settings.appearance.themeTitle"),
            theme_light: s("settings.appearance.themeLight"),
            theme_dark: s("settings.appearance.themeDark"),
            theme_auto: s("settings.appearance.themeAuto"),
            avatar_title: s("settings.appearance.avatarTitle"),
            avatar_initials: s("settings.appearance.avatarInitials"),
            avatar_identicon: s("settings.appearance.avatarIdenticon"),
            text_scale: s("settings.appearance.textScale"),
            currency: s("settings.localization.currencyTitle"),
            number_format: s("settings.localization.numberTitle"),
            number_subtitle: s("settings.localization.numberSubtitle"),
            date_format: s("settings.localization.dateTitle"),
            time_format: s("settings.localization.timeTitle"),
            note_system: s("common.system"),
            note_automatic: s("common.automatic"),
            note_indian: s("settings.formatNote.indian"),
            networks_subtitle: s("settings.advanced.networksSubtitle"),
            add_network: s("settings.advanced.addNetworkTitle"),
            add_network_desc: s("settingsModals.addNetwork.description"),
            search_placeholder: s("settingsModals.addNetwork.searchPlaceholder"),
            chain_id: raw("settingsModals.network.chainId"),
            rpc_url: s("settingsModals.network.fieldRpcUrl"),
            explorer: s("settingsModals.network.fieldExplorer"),
            network_custom: s("settings.networks.custom"),
            network_slow: s("settings.networks.slow"),
            network_save_hint: s("settings.networks.saveHint"),
            compatible: s("settingsModals.addNetwork.compatible"),
            compatibility_check: s("settingsModals.addNetwork.compatibilityCheck"),
            check_safe: s("settingsModals.addNetwork.checkSafe"),
            check_signer: s("settingsModals.addNetwork.checkSigner"),
            check_remaining: raw("settingsModals.addNetwork.checkRemaining"),
            custom_rpc_title: s("settingsModals.addNetwork.customRpcTitle"),
            custom_rpc_placeholder: s("settingsModals.addNetwork.customRpcPlaceholder"),
            best_rpc: raw("settingsModals.addNetwork.bestRpc"),
            providers_desc: s("settingsModals.rpcProviders.description"),
            provider_connected: s("activity.connected"),
            provider_not_set: s("settingsModals.rpcProviders.notSet"),
            provider_check_key: s("settingsModals.rpcProviders.checkKey"),
            provider_get_key: s("settingsModals.rpcProviders.getKey"),
            provider_supports: raw("settingsModals.rpcProviders.supportsCount"),
            provider_avg_latency: raw("settingsModals.rpcProviders.avgLatency"),
            endpoints_desc: s("settingsModals.endpoints.description"),
            endpoint_chain_data: s("settingsModals.endpoints.chainDataLabel"),
            endpoint_chain_data_hint: s("settingsModals.endpoints.chainDataHint"),
            endpoint_passkey: s("settingsModals.endpoints.passkeyLabel"),
            endpoint_passkey_hint: s("settingsModals.endpoints.passkeyHint"),
            endpoint_relay: s("settingsModals.endpoints.bundlerLabel"),
            endpoint_relay_hint: s("settingsModals.endpoints.bundlerHint"),
            endpoint_fiat: s("settingsModals.endpoints.fiatLabel"),
            endpoint_fiat_hint: s("settingsModals.endpoints.fiatHint"),
            endpoints_reset: s("settingsModals.endpoints.resetToDefaults"),
            endpoints_guide: s("settingsModals.endpoints.selfHostGuide"),
            storage_subtitle: s("settings.storage.subtitle"),
            storage_summary: raw("settings.storage.summary"),
            storage_user_data: s("settings.storage.userData"),
            storage_caches: s("settings.storage.caches"),
            storage_connections: s("settings.storage.connections"),
            item_transactions: s("settings.storage.itemTransactions"),
            item_contacts: s("settings.storage.itemContacts"),
            item_custom: s("settings.storage.itemCustom"),
            item_browsing: s("settings.storage.itemBrowsing"),
            item_balances: s("settings.storage.itemBalances"),
            item_rates: s("settings.storage.itemRates"),
            item_scan: s("settings.storage.itemScan"),
            item_dapps: s("settings.storage.itemDapps"),
            count_records: raw("settings.storage.records"),
            count_contacts: raw("settings.storage.contactsCount"),
            count_items: raw("settings.storage.itemsCount"),
            count_sites: raw("settings.storage.sitesCount"),
            storage_clear: s("settings.storage.clear"),
            storage_clear_all: s("settings.storage.clearAllCaches"),
            storage_disconnect_all: s("settings.storage.disconnectAll"),
            about_tagline: s("about.tagline"),
            about_version: raw("about.version"),
            about_section_technical: s("about.sectionTechnical"),
            about_section_links: s("about.sectionLinks"),
            about_wallet_label: s("about.techWalletLabel"),
            about_wallet_value: s("about.techWalletValue"),
            about_auth_label: s("about.techAuthLabel"),
            about_auth_value: s("about.techAuthValue"),
            about_account_label: s("about.techAccountTypeLabel"),
            about_account_value: s("about.techAccountTypeValue"),
            about_signer_label: s("about.techSignerLabel"),
            about_signer_value: s("about.techSignerValue"),
            about_networks_label: s("about.techNetworksLabel"),
            about_networks_value: raw("about.techNetworksValue"),
            about_link_website: s("about.linkWebsite"),
            about_link_github: s("about.linkGitHub"),
            about_link_safe: s("about.linkSafeWallet"),
            about_footer: s("about.footer"),
            rpc_fix_title: s("assets.rpcFixTitle"),
            rpc_fix_warning: s("assets.rpcFixWarning"),
            rpc_fix_label: s("assets.rpcFixLabel"),
            rpc_fix_save: s("assets.rpcFixSaveBtn"),
            rpc_providers_hint: s("assets.rpcProvidersTitle"),
            rpc_report: s("assets.rpcReport"),
            rpc_unavailable_multiple: raw("assets.rpcUnavailableMultiple"),
            rpc_fix_action: s("assets.rpcFix"),
            offline: s("settingsModals.health.offline"),
        }
    }
}
